## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Sat Mar 12 05:53:50 MSK 2016
APP_VERSION_CODE=6750
APP_VERSION_NAME=12.7.3
# forky comment line APP_PACKAGE=org.telegram.messenger
# forky comment line IS_PRIVATE=false
# forky comment line RELEASE_KEY_PASSWORD=android
# forky comment line RELEASE_KEY_ALIAS=androidkey
# forky comment line RELEASE_STORE_PASSWORD=android
# forky comment line org.gradle.jvmargs=-Xmx4096M
# forky code start
org.gradle.jvmargs=-Xmx8G -XX:+UseParallelGC
# forky code end
# forky comment line org.gradle.daemon=true
org.gradle.parallel=true
# forky comment line org.gradle.configureondemand=false
# forky comment line android.useAndroidX=true
# forky comment line android.enableJetifier=true
# forky comment line android.defaults.buildfeatures.buildconfig=true
# forky comment line android.nonTransitiveRClass=false
# forky comment line android.nonFinalResIds=false
# forky comment line android.enableR8.fullMode=true
# forky code start
org.gradle.caching=true
#org.gradle.configuration-cache=true TODO uncomment

NAMESPACE=org.telegram.messenger

APP_ID=org.telegram.messenger
HUAWEI_APP_ID=101184875

API_ID=4
API_HASH=014b35b6184100b085b0d0572f9b5103
# forky code end
