// forky code start
pluginManagement {
    repositories {
        mavenCentral()
        google()
    }
    includeBuild("build-logic")
    includeBuild("build-logic/test-generator")
}
// forky code end
include ':TMessagesProj'
/* forky comment
include ':TMessagesProj_App'
include ':TMessagesProj_AppHuawei'
include ':TMessagesProj_AppHockeyApp'
include ':TMessagesProj_AppStandalone'
include ':TMessagesProj_AppTests'
*/
// forky code start
project(":TMessagesProj").name = "app"

include ':ui'
include ':ui:recycler-view'

include ':feature'
include ':feature:launcher-icons'
// forky code end
